# Generated by Django 4.2.18 on 2025-02-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegendItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('center_lat', models.FloatField(default=37.4979)),
                ('center_lng', models.FloatField(default=127.0286)),
                ('zoom', models.FloatField(default=16)),
                ('min_zoom', models.FloatField(default=10)),
                ('max_zoom', models.FloatField(default=18)),
                ('pitch', models.FloatField(default=45)),
                ('bearing', models.FloatField(default=-17.6)),
                ('flood_layer_url', models.URLField(default='https://www.safemap.go.kr/openApiService/wms/getLayerData.do?apikey=3KTOKO6N-3KTO-3KTO-3KTO-3KTOKO6N9R&LAYERS=A2SM_FLUDMARKS&STYLES=A2SM_FludMarks&FORMAT=image/png')),
            ],
        ),
    ]
