# Generated by Django 4.2.18 on 2025-02-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legenditem',
            options={'verbose_name': '범례 항목', 'verbose_name_plural': '범례 항목'},
        ),
        migrations.AlterModelOptions(
            name='mapconfig',
            options={'verbose_name': '지도 설정', 'verbose_name_plural': '지도 설정'},
        ),
        migrations.AlterField(
            model_name='legenditem',
            name='color',
            field=models.CharField(max_length=7, verbose_name='색상 코드'),
        ),
        migrations.AlterField(
            model_name='legenditem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='등급 이름'),
        ),
        migrations.AlterField(
            model_name='legenditem',
            name='range',
            field=models.CharField(max_length=100, verbose_name='범위 설명'),
        ),
        migrations.AlterField(
            model_name='mapconfig',
            name='access_token',
            field=models.CharField(max_length=255, verbose_name='맵박스 액세스 토큰'),
        ),
        migrations.AlterField(
            model_name='mapconfig',
            name='bearing',
            field=models.FloatField(default=-17.6, verbose_name='회전 각도'),
        ),
        migrations.AlterField(
            model_name='mapconfig',
            name='center_lat',
            field=models.FloatField(default=37.4979, verbose_name='기본 위도'),
        ),
        migrations.AlterField(
            model_name='mapconfig',
            name='center_lng',
            field=models.FloatField(default=127.0286, verbose_name='기본 경도'),
        ),
        migrations.AlterField(
            model_name='mapconfig',
            name='flood_layer_url',
            field=models.URLField(default='https://www.safemap.go.kr/openApiService/wms/getLayerData.do', max_length=600, verbose_name='침수 레이어 URL'),
        ),
        migrations.AlterField(
            model_name='mapconfig',
            name='max_zoom',
            field=models.FloatField(default=18, verbose_name='최대 줌'),
        ),
        migrations.AlterField(
            model_name='mapconfig',
            name='min_zoom',
            field=models.FloatField(default=10, verbose_name='최소 줌'),
        ),
        migrations.AlterField(
            model_name='mapconfig',
            name='pitch',
            field=models.FloatField(default=45, verbose_name='3D 각도'),
        ),
        migrations.AlterField(
            model_name='mapconfig',
            name='zoom',
            field=models.FloatField(default=16, verbose_name='초기 줌 레벨'),
        ),
    ]
