# Generated by Django 4.2.18 on 2025-02-10 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0003_blockcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('state_img_url', models.URLField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.block')),
            ],
        ),
        migrations.CreateModel(
            name='DrainRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateTimeField(auto_now_add=True)),
                ('repair_result', models.TextField()),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drain.drain')),
            ],
        ),
        migrations.CreateModel(
            name='DrainCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(default='', max_length=30)),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drain.drain')),
            ],
        ),
    ]
