# Generated by Django 4.2.18 on 2025-02-10 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0003_blockcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_drain', models.CharField(blank=True, max_length=50, null=True)),
                ('is_robot_available', models.BooleanField()),
                ('robot_unavailable_reason', models.TextField(blank=True, default='')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.district')),
            ],
        ),
        migrations.CreateModel(
            name='RobotRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateTimeField(auto_now_add=True)),
                ('repair_reason', models.TextField()),
                ('repair_result', models.TextField()),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot_info.robot')),
            ],
        ),
        migrations.CreateModel(
            name='RobotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(max_length=20)),
                ('log_content', models.TextField()),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot_info.robot')),
            ],
        ),
    ]
