# Generated by Django 4.2.18 on 2025-02-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
