# Generated by Django 4.2.18 on 2025-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('precipitation', models.CharField(max_length=10)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.CharField(max_length=10)),
                ('sky_condition', models.CharField(max_length=10)),
                ('precipitation_type', models.CharField(max_length=10)),
                ('feels_like', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_date', models.CharField(max_length=8)),
                ('base_time', models.CharField(max_length=4)),
            ],
        ),
    ]
