# Generated by Django 4.2.18 on 2025-01-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('current', '현재'), ('after_3h', '3시간 후'), ('after_24h', '24시간 후')], max_length=10)),
                ('temperature', models.FloatField()),
                ('precipitation', models.CharField(max_length=10)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.CharField(max_length=10)),
                ('sky_condition', models.CharField(max_length=10)),
                ('precipitation_type', models.CharField(max_length=10)),
                ('feels_like', models.FloatField()),
                ('base_date', models.CharField(max_length=8)),
                ('base_time', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='WeatherAlert',
        ),
    ]
