# Generated by Django 4.2.18 on 2025-02-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='selected_robot',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
