# Generated by Django 4.2.18 on 2025-02-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_blockcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='block',
            name='location_y',
        ),
    ]
