# Generated by Django 4.2.18 on 2025-02-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_remove_block_location_x_remove_block_location_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='Flood_Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
